from django.test import TestCase, Client
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.core.files.uploadedfile import SimpleUploadedFile
from django.core.exceptions import PermissionDenied
from blog.models import Category, Tag, Post, Comment, PostLike

User = get_user_model()


class MultiAuthorBlogTestCase(TestCase):
    def setUp(self):
        # Create users
        self.reader = User.objects.create_user(username='reader1', password='password123', is_author=False)
        self.author1 = User.objects.create_user(username='author1', password='password123', is_author=True)
        self.author2 = User.objects.create_user(username='author2', password='password123', is_author=True)
        self.admin = User.objects.create_superuser(username='admin', password='password123', email='admin@test.com')

        # Create Category and Tag
        self.category = Category.objects.create(name='Technology')
        self.tag1 = Tag.objects.create(name='Django')
        self.tag2 = Tag.objects.create(name='Python')

        # Create sample image
        tiny_png = (
            b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01'
            b'\x08\x06\x00\x00\x00\x1f\x15c4\x00\x00\x00\rIDATx\x9cc`\x00\x00\x00'
            b'\x02\x00\x01H\xafA4\x00\x00\x00\x00IEND\xaeB`\x82'
        )
        self.image = SimpleUploadedFile("test_image.png", tiny_png, content_type="image/png")

        # Create Published Post by author1
        self.pub_post = Post.objects.create(
            title='Django Web Development',
            content='Full guide on building Django apps.',
            featured_image=self.image,
            category=self.category,
            author=self.author1,
            status='PUBLISHED'
        )
        self.pub_post.tags.add(self.tag1)

        # Create Draft Post by author1
        self.draft_post = Post.objects.create(
            title='Draft Article Ideas',
            content='Work in progress thoughts.',
            featured_image=self.image,
            category=self.category,
            author=self.author1,
            status='DRAFT'
        )

        self.client = Client()

    def test_default_user_is_reader(self):
        user = User.objects.create_user(username='new_user', password='password123')
        self.assertFalse(user.is_author)
        self.assertFalse(user.is_staff)

    def test_admin_can_promote_user(self):
        self.reader.is_author = True
        self.reader.save()
        updated = User.objects.get(pk=self.reader.pk)
        self.assertTrue(updated.is_author)

    def test_post_slug_autogenerated(self):
        post = Post.objects.create(
            title='Test Auto Slug Generation',
            content='Content here',
            featured_image=self.image,
            category=self.category,
            author=self.author1,
            status='PUBLISHED'
        )
        self.assertEqual(post.slug, 'test-auto-slug-generation')

    def test_homepage_shows_only_published_posts(self):
        response = self.client.get(reverse('index'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, self.pub_post.title)
        self.assertNotContains(response, self.draft_post.title)

    def test_draft_post_visibility_protection(self):
        # Anonymous user cannot view draft
        resp = self.client.get(reverse('post_detail', kwargs={'slug': self.draft_post.slug}))
        self.assertEqual(resp.status_code, 404)

        # Reader cannot view draft
        self.client.login(username='reader1', password='password123')
        resp = self.client.get(reverse('post_detail', kwargs={'slug': self.draft_post.slug}))
        self.assertEqual(resp.status_code, 404)

        # Author of draft CAN view draft
        self.client.login(username='author1', password='password123')
        resp = self.client.get(reverse('post_detail', kwargs={'slug': self.draft_post.slug}))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, self.draft_post.title)

    def test_author_post_ownership_protection(self):
        # Author2 tries to edit Author1's post -> Blocked (403 Forbidden / PermissionDenied)
        self.client.login(username='author2', password='password123')
        resp = self.client.get(reverse('post_edit', kwargs={'slug': self.pub_post.slug}))
        self.assertEqual(resp.status_code, 403)

        # Author2 tries to delete Author1's post -> Blocked (403)
        resp = self.client.post(reverse('post_delete', kwargs={'slug': self.pub_post.slug}))
        self.assertEqual(resp.status_code, 403)

        # Author1 CAN access edit form for their own post
        self.client.login(username='author1', password='password123')
        resp = self.client.get(reverse('post_edit', kwargs={'slug': self.pub_post.slug}))
        self.assertEqual(resp.status_code, 200)

    def test_non_author_cannot_create_post(self):
        self.client.login(username='reader1', password='password123')
        resp = self.client.get(reverse('post_create'))
        self.assertEqual(resp.status_code, 403)

    def test_view_count_increments(self):
        initial_views = self.pub_post.view_count
        resp = self.client.get(reverse('post_detail', kwargs={'slug': self.pub_post.slug}))
        self.assertEqual(resp.status_code, 200)
        self.pub_post.refresh_from_db()
        self.assertEqual(self.pub_post.view_count, initial_views + 1)

    def test_like_system_toggle(self):
        self.client.login(username='reader1', password='password123')
        url = reverse('like_toggle', kwargs={'slug': self.pub_post.slug})

        # Like
        self.client.post(url)
        self.assertEqual(PostLike.objects.filter(post=self.pub_post, user=self.reader).count(), 1)

        # Unlike (toggle)
        self.client.post(url)
        self.assertEqual(PostLike.objects.filter(post=self.pub_post, user=self.reader).count(), 0)

    def test_comment_system_and_moderation(self):
        # Reader posts a comment
        self.client.login(username='reader1', password='password123')
        create_url = reverse('comment_create', kwargs={'slug': self.pub_post.slug})
        self.client.post(create_url, {'text': 'Awesome Django post!'})

        comment = Comment.objects.get(post=self.pub_post, user=self.reader)
        self.assertEqual(comment.text, 'Awesome Django post!')

        # Another reader cannot delete reader1's comment
        user3 = User.objects.create_user(username='reader2', password='password123')
        self.client.login(username='reader2', password='password123')
        del_url = reverse('comment_delete', kwargs={'pk': comment.pk})
        resp = self.client.get(del_url)
        self.assertEqual(resp.status_code, 403)

        # Post author CAN delete reader1's comment (Moderation requirement)
        self.client.login(username='author1', password='password123')
        resp = self.client.get(del_url)
        self.assertEqual(resp.status_code, 302)
        self.assertFalse(Comment.objects.filter(pk=comment.pk).exists())

    def test_search_functionality(self):
        resp = self.client.get(reverse('index') + '?q=Django')
        self.assertContains(resp, self.pub_post.title)

        resp = self.client.get(reverse('index') + '?q=NonExistentKeyword')
        self.assertNotContains(resp, self.pub_post.title)

    def test_admin_dashboard_access_and_crud(self):
        # Reader cannot access admin dashboard -> 403 Forbidden
        self.client.login(username='reader1', password='password123')
        resp = self.client.get(reverse('admin_dashboard'))
        self.assertEqual(resp.status_code, 403)

        # Admin CAN access admin dashboard -> 200 OK
        self.client.login(username='admin', password='password123')
        resp = self.client.get(reverse('admin_dashboard'))
        self.assertEqual(resp.status_code, 200)

        # Admin toggles reader1 role to Author
        toggle_url = reverse('admin_user_toggle_author', kwargs={'pk': self.reader.pk})
        self.client.get(toggle_url)
        self.reader.refresh_from_db()
        self.assertTrue(self.reader.is_author)

        # Admin creates new category via Custom Admin Panel
        create_cat_url = reverse('admin_category_create')
        self.client.post(create_cat_url, {'name': 'Science', 'description': 'Research & Discoveries'})
        self.assertTrue(Category.objects.filter(name='Science').exists())

